#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main()
{
    printf("\tWELCOME TO THE NUMBER GUESSING GAME\t\n");
    srand(time(0));
    int num = rand() % (100 - 1 + 1) + 1;
    printf("A random number has been generated by the system,\nGuess the number in fewest attempts to win the game.\n");
    printf("-----------------------------------------------------\n");
    printf("\t\tBASIC DIRECTIONS\t\t\n");
    printf("The player has to make a guess between 1 and 100.\nIf the guess is lower than the correct answer,\n\"LOW!,Try Again.\"\nmessage will appear.\n");
    printf("If the guess is higher than the correct answer,\n\"HIGH!,Try Again.\"\nmessage will appear.\n");
    printf("-----------------------------------------------------\n");
    int count = 0;
    int guess;
    for (int i = 1; i; i++)
    {
        printf("Please enter guess no. %d: ", i);
        scanf("%d", &guess);
        count += 1;
        if (guess == num)
        {
            printf("CONGRATULATIONS, You guessed the correct number in %d tries.\n", count);
            printf("Thanks for playing!\n");
            break;
        }
        else if (guess < num)
        {
            printf("LOW!,Try Again.\n");
            printf("Guess counter: %d\n", count);
        }
        else
        {
            printf("HIGH!,Try Again\n");
            printf("Guess counter: %d\n", count);
        }
    }
    return 0;
}